# Generated by Django 4.2.6 on 2023-10-28 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('sketch_number', models.SmallIntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=1, max_digits=7)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_autor', models.CharField(max_length=20)),
                ('review_autor', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_sign', models.CharField(default='Синий', max_length=50)),
                ('address_sign', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('form_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.address')),
            ],
        ),
    ]
